### PR TITLE
Add Hammer config file to enable module.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Would be great to get a new gem release after this update, see -- https://github.com/theforeman/foreman-packaging/pull/593#issuecomment-83946172

**Comment by komidore64** [comment]
ack

**Comment by komidore64** [comment]
errr, hold on.

is the rpm already installing this file? if, i'd say that needs to be in this PR as well.

**Comment by komidore64** [comment]
ack

**Comment by komidore64** [comment]
ack

**Pull request merged**
